#!/bin/bash

BUILD_TYPE=Release
BUILD_DIR=build

if [[ ! -d $BUILD_DIR ]]; then
    cmake . -B $BUILD_DIR -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DTRIPLE_VERIFY=OFF -DTRIPLE_COLOR=OFF -DUSE_APPROX_RESHARE=OFF -DTRIPLE_ZERO=ON
fi

cmake --build build -j
